# This is a basic workflow to help you get started with Actions

name: Formatter updater

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 'alpine:edge'
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Get and compress formatters
        run: |
          apk update
          apk --no-cache upgrade
          apk --no-cache add gcc musl-dev binutils go cmake make alpine-sdk git g++ curl rust ninja wget
          mkdir $GITHUB_WORKSPACE/formatters
          cp $(which rustfmt) $GITHUB_WORKSPACE/formatters
          cp $(which gofmt) $GITHUB_WORKSPACE/formatters
          go get -u github.com/klauspost/asmfmt/cmd/asmfmt
          export GOPATH=$(go env | grep GOPATH | cut -d= -f2 | tr -d \")
          export PATH=$PATH:$GOPATH/bin
          cp $(which asmfmt) $GITHUB_WORKSPACE/formatters
          echo here
          curl -s "https://api.github.com/repos/tweag/ormolu/releases/latest" | grep "ormolu-Linux" | cut -d : -f 2,3 | tr -d \" | tail -n1 | tr -d ' ' | wget -qi - -O $GITHUB_WORKSPACE/formatters/ormolu
          cd $GITHUB_WORKSPACE/formatters
          chmod +x ormolu
          git clone https://github.com/Koihik/LuaFormatter.git
          cd LuaFormatter
          git submodule update --init --recursive
          cmake -GNinja .
          ninja -j50
          cp lua-format $GITHUB_WORKSPACE/formatters
          cd $GITHUB_WORKSPACE/formatters
          rm -rf LuaFormatter
          curl -s "https://api.github.com/repos/pinterest/ktlint/releases/latest" | grep "ktlint" | cut -d : -f 2,3 | tr -d \" | grep download | head -n1 | tr -d ' ' | wget -i - -O $GITHUB_WORKSPACE/formatters/ktlint
          tar -czvf formatters.tar.gz formatters
          rm -rf formatters
      - uses: actions/upload-artifact@v2
        with:
          name: formatters.tar.gz
          path: formatters.tar.gz
          
